services:
  atm-adapter:
    image: quarkus/atm-adapter-native-distroless
    restart: always
    ports:
      - "8082:8080"
    networks:
      - atm-adapter-network
    environment:
      QUARKUS_MONGODB_CONNECTION_STRING: mongodb://mongo:27017
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - './mongo_data:/data/db'
      - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:ro'
    environment:
      MONGO_INITDB_DATABASE: atm_data_db
    networks:
      - atm-adapter-network
volumes:
  mongo_data:
    driver: local

networks:
  atm-adapter-network: