quarkus:
  application:
    name: atm-adapter
  log:
    console:
      format: "%d{HH:mm:ss} %-5p [%X{X-Correlation-ID}] %c - %m%n"
  mongodb:
    connection-string: ${aws.secretsmanager.atm/locations/local/mongodb/connection-string}
    database: atm_data_db
  otel:
    metrics:
      enabled: true
    exporter:
      otlp:
        enabled: true
        protocol: grpc
        endpoint: http://localhost:4317
  secretsmanager:
    endpoint-override: http://localhost:4566
    aws:
      region: us-east-1
      credentials:
        static-provider:
          access-key-id: test-key
          secret-access-key: test-secret
        type: static

